import { AdaptiveWater } from "@engine/core/adaptive_water";
import { Terrain } from "@engine/core/terrain";
import { GameObject } from "@engine/core/gameobject";
import { scene } from "@editor/control/session";
import { history } from "@editor/undo";
import { playMode } from "@editor/play_mode";
import { sceneFromJSON,sceneToJSON } from "@editor/sceneio";
function check(ok:boolean,msg:string):void {if(!ok)throw new Error(msg);}
scene.clear();const ground=new GameObject("Terrain"),terrain=new Terrain();ground.addBehavior(terrain);scene.add(ground);
const go=new GameObject("Water"),water=new AdaptiveWater();water.resolution=8;water.sourceRate=4;go.addBehavior(water);scene.add(go);scene.computeWorld();
water.previewSecond();check(water.error()===""&&Math.abs(water.volume()-4)<.000001,"fonte adiciona volume");
history.snapshot();check(water.bake(),"bake");const state=water.bakedState;
water.update(.05);check(water.bakedState===state&&Math.abs(water.volume()-4)<.000001,"congelado nao simula");
const saved=sceneToJSON();check(saved.includes("bakedState"),"snapshot salvo na cena");
check(playMode.play(),"Play");const playing=scene.objects[1].behaviors[0] as AdaptiveWater;
playing.update(.05);check(Math.abs(playing.volume()-4)<.000001,"copia restaura snapshot");
playing.dynamic=true;playing.update(.05);check(playing.volume()>4&&Math.abs(water.volume()-4)<.000001,"Play independente");
playMode.stop();check(scene.objects[1]===go&&!water.dynamic,"Stop preserva autoria");
sceneFromJSON(saved);scene.computeWorld();const loaded=scene.objects[1].behaviors[0] as AdaptiveWater;
loaded.update(.05);check(Math.abs(loaded.volume()-4)<.000001&&!loaded.dynamic,"reload congelado");
history.snapshot();loaded.previewSecond();loaded.bake();check(Math.abs(loaded.volume()-8)<.000001,"prepara segundo estado");history.undo();
const undone=scene.objects[1].behaviors[0] as AdaptiveWater;undone.update(.05);check(Math.abs(undone.volume()-4)<.000001,"Desfazer restaura snapshot");
history.redo();const redone=scene.objects[1].behaviors[0] as AdaptiveWater;redone.update(.05);check(Math.abs(redone.volume()-8)<.000001,"Refazer restaura snapshot");
check(!redone.sample(NaN,0,new Float64Array(4)),"consulta invalida");
const groundLoaded=scene.objects[0].behaviors[0] as Terrain;groundLoaded.brush(0,0,10,2);
redone.releaseResources();redone.update(.05);check(redone.error()!==""&&redone.volume()===0,"recusa snapshot de leito alterado");
redone.resetSimulation();check(redone.error()===""&&redone.volume()===0,"reinicio relê terreno");
redone.dynamic=true;for(let i=0;i<100;i++)redone.update(.01);check(Math.abs(redone.volume()-4)<.000001,"tempo fixo preserva resto em 100 FPS");
redone.resetSimulation();for(let i=0;i<40;i++)redone.update(.025);check(Math.abs(redone.volume()-4)<.000001,"mesmo volume em 40 FPS");
redone.resetSimulation();redone.update(10);check(Math.abs(redone.volume()-.2)<.000001,"limita catch-up a um passo");
scene.clear();console.log("adaptive-water-editor OK: bake, cena, Play/Stop e leito alterado");
