import fs from "@compat/fs.ts";
import { AudioClip, acquireAudioClip, clipPorId, clearAudioClipCache, clipDecodificacoes } from "@engine/audio/clip";
import { resourceCache } from "@engine/core/resources";
import { initAudio, AUDIO_NULO, closeAudio, tocarClipe, agendarEm, cancelarAgendado, mixarBloco, pararTodas, pararTodasSuave, pausarVoz, pararVoz, vozTocando } from "@engine/audio/audio";
import { novoPedido, PEDIDO_LACO, PEDIDO_VOLUME, MAX_VOZES } from "@engine/audio/vozes";
import { mixerSetPausa } from "@engine/audio/mixer_grupos";
import { AudioSource } from "@scripts/audiosource";
import { EspecWav, escreverWav } from "./wav_escritor";
function check(ok:boolean,message:string):void { if(!ok)throw new Error(message); }
initAudio(AUDIO_NULO);
const path="build/test-audio/resource-lifecycle.wav";
fs.create_dir_all("build/test-audio");const wav=new EspecWav();wav.quadros=4800;wav.taxa=48000;wav.canais=1;fs.write(path,escreverWav(wav));
const cache=resourceCache<any>("audio");
const a=new AudioSource(),b=new AudioSource();a.clip=path;b.clip="./"+path;a.loop=true;b.loop=true;
const decodes=clipDecodificacoes();a.play();b.play();
check(cache.stats().entries===1&&cache.stats().references===4&&cache.stats().pinned===0,"duas fontes e vozes compartilham arquivo");
check(clipDecodificacoes()===decodes+1,"caminhos equivalentes decodificam uma vez");
a.releaseResources();mixarBloco(64);check(cache.stats().references===2&&b.isPlaying(),"remover fonte preserva outra");
b.releaseResources();check(cache.stats().references===1,"rampa de parada ainda possui amostras");mixarBloco(64);check(cache.stats().entries===0,"fim da rampa libera ultimo dono");
const request=novoPedido();
const shot=acquireAudioClip(path)!;const shotId=shot.value.id;
const source=new AudioSource();const voice=source.playOneShot(shot.value,1);shot.release();source.releaseResources();
check(vozTocando(voice)!==0&&clipPorId(shotId)!==null,"oneshot sobrevive a fonte e referencia do chamador");
for(let i=0;i<4;i++)mixarBloco(2400);
check(cache.stats().entries===0&&clipPorId(shotId)===null,"fim natural remove clipe da tabela global");
const scheduled=acquireAudioClip(path)!;const id=agendarEm(scheduled.value,1000,request);scheduled.release();
check(cache.stats().references===1,"agenda preserva clipe antes de existir voz");
check(cancelarAgendado(id)===1&&cache.stats().entries===0,"cancelar agenda libera clipe");
const due=acquireAudioClip(path)!;agendarEm(due.value,0,request);due.release();mixarBloco(64);
check(cache.stats().references===1,"agenda transfere propriedade para voz");
pararTodas();check(cache.stats().entries===0,"teardown limpa buffers de voz");
const future=acquireAudioClip(path)!;agendarEm(future.value,1000,request);future.release();pararTodasSuave();
check(cache.stats().entries===0,"parar jogo cancela sons futuros");
const paused=acquireAudioClip(path)!;request[PEDIDO_LACO]=1;const pausedId=tocarClipe(paused.value,request);paused.release();pausarVoz(pausedId,1);mixarBloco(64);
check(cache.stats().references===1,"pausa preserva amostras");pararVoz(pausedId);check(cache.stats().entries===0,"parar voz ja pausada libera imediatamente");
const virtual=acquireAudioClip(path)!;request[PEDIDO_VOLUME]=0;
for(let i=0;i<MAX_VOZES+1;i++)check(tocarClipe(virtual.value,request)>0,"voz virtual pode ceder slot");
virtual.release();check(cache.stats().references===MAX_VOZES,"roubo nao acumula referencias");pararTodas();check(cache.stats().entries===0,"limpeza de todos os slots");
const frozen=acquireAudioClip(path)!;mixerSetPausa(0,1);request[PEDIDO_VOLUME]=1;
const frozenId=tocarClipe(frozen.value,request);frozen.release();pararVoz(frozenId);mixarBloco(64);
check(cache.stats().entries===0,"parada libera voz mesmo com grupo congelado");mixerSetPausa(0,0);
const old=AudioClip.load(path)!;const managed=acquireAudioClip(path)!;clearAudioClipCache();
check(clipPorId(old.id)===old,"evict preserva consumidor ativo");managed.release();check(clipPorId(old.id)===null,"evict e ultima referencia descartam clipe legado");
const final=acquireAudioClip(path)!;agendarEm(final.value,1000,request);final.release();closeAudio();check(cache.stats().entries===0,"fechar dispositivo libera agenda");
console.log("resources-audio-lifecycle OK");
