import io from "@compat/io.ts";
import { createComponent, componentToData } from "@engine/components";
import { MotionSettings } from "../assets/scripts/MotionSettings";
import { GameObject } from "@engine/core/gameobject";
import { recreateBehavior, objectToData, buildObject } from "@editor/sceneio";
import { COMPONENT_NAMES } from "@editor/component_catalog";
import { scene, S } from "@editor/control/session";
import { playMode } from "@editor/play_mode";

function check(condition: boolean, message: string): void {
  if (!condition) throw new Error(message);
}
check(COMPONENT_NAMES.indexOf("MotionSettings") >= 0, "script discovered without manual registry");
const direct = new MotionSettings();
check(direct.createHelper().typeName() === "Spinner", "scripts can instantiate other registered components");
check(direct.typeName() === "MotionSettings" && direct.fieldCount() === 3, "direct new receives metadata, private hidden");
const component = createComponent("MotionSettings");
check(component instanceof MotionSettings, "factory creates actual script class");
check(component.fieldType(0) === "number" && component.fieldType(1) === "boolean" && component.fieldType(2) === "string", "types inferred from source");
check(component.fieldLabel(0) === "Speed", "label derived from field name");
component.fieldSet(0, 999);
check(component.fieldGet(0) === 20, "range clamped");
component.fieldSet(0, 3.5); component.fieldSet(1, 0); component.fieldStringSet(2, "Minha nave");
check(component.fieldGet(0) === 3.5 && component.fieldGet(1) === 0 && component.fieldStringGet(2) === "Minha nave", "numeric boolean string write to class");
const serialized = component.toData();
check(serialized.fields.elapsed === undefined, "private runtime state not serialized");
const loaded = recreateBehavior(serialized);
check(loaded.typeName() === "MotionSettings" && loaded.fieldGet(0) === 3.5 && loaded.fieldStringGet(2) === "Minha nave", "automatic round-trip");
const go = new GameObject("Script"); go.addBehavior(component);
const copy = buildObject(objectToData(go));
check(copy.behaviors[0].fieldGet(1) === 0 && copy.behaviors[0].fieldStringGet(2) === "Minha nave", "scene stores per-instance values");
const fresh = createComponent("MotionSettings");
check(fresh.fieldGet(0) === 2 && fresh.fieldGet(1) === 1, "another instance retains source defaults");
go.behaviors[0].fieldSet(1, 1); go.update(1);
check(go.transform.px === 3.5, "script logic uses edited fields");
scene.clear(); scene.add(go); S.selected = 0;
check(playMode.play(), "automatic component can enter play mode");
scene.objects[0].behaviors[0].fieldStringSet(2, "Runtime");
scene.update(1); playMode.stop();
check(scene.objects[0] === go && go.behaviors[0].fieldStringGet(2) === "Minha nave", "stop restores original auto component");
const spinner = createComponent("Spinner");
check(spinner.fieldCount() === 2 && spinner.fieldLabel(0) === "SpdY", "built-in migrated to generated fields");
spinner.fieldSet(0, 8); check(spinner.fieldGet(0) === 8, "built-in auto setter");
const legacy = componentToData(spinner);
check(legacy.type === "spin" && legacy.componentFields.speedY === 8, "legacy format also captures automatic fields");
check(recreateBehavior(legacy).fieldGet(0) === 8, "legacy and automatic fields restore together");
const missingData = { type: "script:removed.ts#Removed", fields: { speed: 9, label: "Preservar" } };
const missing = recreateBehavior(missingData);
check(missing.typeName().indexOf("Script ausente") === 0 && missing.toData().fields.label === "Preservar", "missing scripts retain serialized data");
scene.clear(); scene.createGameObject("Missing").addBehavior(missing);
check(!playMode.play() && S.simulating === 0, "missing script blocks simulation without damaging scene");
io.print("[PASSOU] Component reflection: descoberta, campos, tipos, cena, defaults e Play");
